"""
Lightweight protocol interfaces describing the expected behavior of all
configuration models. These are used for dependency injection and to keep
higher-level components independent from concrete config implementations.
"""

from typing import Protocol, List, Dict, Union, Any, Optional


# Storage Config Interface

class StorageConfigInterface(Protocol):
    def get_s3_endpoint(self) -> str: ...
    def get_s3_access_key(self) -> str: ...
    def get_s3_secret_key(self) -> str: ...


# Domain Config Interface

class DomainConfigInterface(Protocol):
    def get_earth_equatorial_radius_km(self) -> float: ...
    def get_earth_gravitational_parameter(self) -> float: ...
    def get_risk_thresholds(self) -> Dict[str, float]: ...


# Catalog Config Interface

class CatalogConfigInterface(Protocol):
    def get_dynamic_selection_seed(self) -> int: ...
    def get_calibration_count(self) -> int: ...
    def get_calibration_query(self) -> str: ...
    def get_target_count(self) -> int: ...
    def get_target_query(self) -> str: ...
    def get_min_orbit_days(self) -> int: ...
    def get_anchor_calibration_ids(self) -> List[str]: ...
    def get_solar_cycle_regimes(self) -> Dict[str, List[List[int]]]: ...
    def get_calibration_period_bands(self) -> Dict[str, int]: ...


# Processing Config Interface

class ProcessingConfigInterface(Protocol):
    def get_max_workers(self) -> int: ...
    def get_batch_limits(self) -> Dict[str, Any]: ...
    def get_numeric_omm_fields(self) -> List[str]: ...
    def get_critical_columns(self) -> List[str]: ...
    def get_angular_columns(self) -> List[str]: ...
    def get_sentinel_values(self) -> List[str]: ...
    def get_static_columns_to_keep(self) -> List[str]: ...
    def filter_tba_objects(self) -> bool: ...
    def get_date_range(self) -> Dict[str, str]: ...
    def is_quality_check_enabled(self) -> bool: ...
    def get_min_data_points(self) -> int: ...
    def get_max_gap_days(self) -> int: ...
    def is_orbit_classification_enabled(self) -> bool: ...
    def is_position_calculation_enabled(self) -> bool: ...
    def get_orbital_cleaning_config(self) -> Dict[str, Dict[str, Any]]: ...
    def get_orbital_segmentation_config(self) -> Dict[str, Dict[str, float]]: ...
    def get_segment_filter_config(self) -> Dict[str, Dict[str, Any]]: ...
    def get_orbital_propagation_config(self) -> Dict[str, Dict[str, Any]]: ...
    def get_far_from_tle_minutes(self) -> int: ...


# Scheduling Config Interface

class SchedulingConfigInterface(Protocol):
    def is_model_training_enabled(self) -> bool: ...
    def get_daily_reports_schedule(self) -> str: ...


# Logging Config Interface

class LoggingConfigInterface(Protocol):
    def get_log_level(self) -> str: ...
    def get_log_files(self) -> Dict[str, str]: ...
    def get_environment_name(self) -> str: ...


# Machine Learning Config Interface

class MLConfigInterface(Protocol):
    def get_mlflow_tracking_uri(self) -> str: ...
    def get_default_model_registry_name(self) -> str: ...
    def is_orbital_features_enabled(self) -> bool: ...
    def get_mlflow_experiment_name(self) -> str: ...
    def get_lstm_params(self) -> Dict[str, Any]: ...
    def get_mlflow_production_run_id(self) -> str: ...
    def get_risk_score_thresholds(self) -> Dict[str, float]: ...


# Monitoring Config Interface

class MonitoringConfigInterface(Protocol):
    def is_prometheus_enabled(self) -> bool: ...
    def get_failed_request_alert_rate(self) -> float: ...
    def is_compliance_monitoring_enabled(self) -> bool: ...
    def get_compliance_daily_warning(self) -> float: ...
    def get_compliance_hourly_warning(self) -> float: ...
    def get_compliance_burst_warning(self) -> float: ...
    def get_compliance_daily_critical(self) -> float: ...
    def get_cache_hit_rate_threshold(self) -> float: ...
    def get_cache_size_alert_mb(self) -> int: ...
    def is_cache_monitoring_enabled(self) -> bool: ...
    def get_collection_time_threshold(self) -> int: ...
    def is_api_usage_tracking_enabled(self) -> bool: ...
    def is_compliance_alerts_enabled(self) -> bool: ...
    def get_high_risk_satellites_alert(self) -> int: ...
    def get_processing_time_threshold_alert(self) -> int: ...
    def is_health_checks_enabled(self) -> bool: ...
    def get_metrics_collection_interval(self) -> int: ...


# Pipeline Config Interface

class PipelineConfigInterface(Protocol):
    execution_mode: Optional[str]
    target_date: Optional[str]

    def get_s3_bucket(self, bucket_name: str) -> str: ...
    def get_s3_prefix(self, prefix_name: str) -> str: ...
    def get_space_track_username(self) -> str: ...
    def get_space_track_password(self) -> str: ...
    def get_space_track_daily_limit(self) -> int: ...
    def get_smart_collection_force_refresh_days(self) -> int: ...
    def get_flux_header_skip_lines(self) -> int: ...
    def is_incremental_updates_enabled(self) -> bool: ...
    def get_incremental_max_days(self) -> int: ...
    def get_incremental_overlap_hours(self) -> int: ...
    def get_incremental_buffer_size(self) -> int: ...
    def get_env_sources(self) -> Dict[str, Dict[str, Any]]: ...
    def get_env_source_url(self, source_id: str) -> str: ...
    def is_duplicate_detection_enabled(self) -> bool: ...
    def get_cache_max_size_mb(self) -> int: ...
    def get_space_track_base_url(self) -> str: ...
    def get_space_track_hourly_limit(self) -> int: ...
    def get_space_track_burst_limit(self) -> int: ...
    def get_space_track_api_delay(self) -> int: ...
    def get_space_track_max_retries(self) -> int: ...
    def get_batch_timeout_multiplier(self) -> float: ...
    def get_retry_backoff_factor(self) -> float: ...
    def get_space_track_session_timeout(self) -> int: ...
    def get_full_batch_size(self) -> int: ...
    def get_inc_batch_size(self) -> int: ...
    def use_space_track_test_server(self) -> bool: ...
    def get_space_track_endpoint(self, endpoint_name: str) -> Union[str, List[str]]: ...
    def get_rate_limit_buffer(self) -> int: ...
    def get_solar_flux_url(self) -> str: ...
    def get_kp_indices_url(self) -> str: ...
    def get_sunspot_url(self) -> str: ...
